title: My test awesome title
author: Hunterhawk
email: bjwgwgfy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  lalala lalala Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: hunterhawk-twitter
github_username:  hunterhawk

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
